name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t itiburski/docker-course-ci-cd-workflow-test -f Dockerfile.dev .
      - run: docker run -e CI=true itiburski/docker-course-ci-cd-workflow-test npm test

      - name: Generate deployment package
        run: zip -r docker-course-ci-cd-workflow.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-course-ci-cd-workflow
          environment_name: Docker-course-ci-cd-workflow-env
          existing_bucket_name: elasticbeanstalk-sa-east-1-423623840381
          region: sa-east-1
          version_label: ${{ github.sha }}
          deployment_package: docker-course-ci-cd-workflow.zip